### ISSUE TITLE
Could this package support versions below v1.6?

### ISSUE THREAD

**Issue by singularitti** [poncito/AnonymousEnums.jl#4]
I am [using this package in my code](https://github.com/MineralsCloud/CrystallographyBase.jl/blob/9e0fa2777938c8e65057f717d8a083e837b46113/Project.toml#L14). Thank you for developing it! I just wonder if this package used some v1.6-specific features so that it cannot be installed on versions under v1.6?

**Comment by poncito** [comment]
Hey!

Actually I don’t think it would be an issue.

Let me setup the continuous integration for older Julia versions, and I’ll
remove the constraint. Or if you feel like it, you can write the PR. But I
should be able to do it today.
Thanks for pointing that out!

Romain

**Comment by singularitti** [comment]
Thank you Romain! I could write a PR.
